import type { Template } from "../types";

/**
 * 3-slide portrait list: hook + two numbered entries. Reads like a
 * mini personal-recommendation post.
 */
const W = 1080;

export const template: Template = {
  id: "ig-portrait-numbered",
  name: "Numbered Recs",
  description: "Hook + two numbered cards. Swap titles to share what you're reading, watching, listening to.",
  presetId: "ig-portrait",
  slideCount: 3,
  tags: ["recommendation", "list"],
  background: { kind: "solid", color: "#F4F1EA" },
  elements: [
    // ── Slide 0 — hook ──────────────────────────────────────────────
    {
      id: "tpl-num-cover-eyebrow",
      kind: "text",
      z: 1,
      x: 100,
      y: 280,
      width: 880,
      height: 60,
      rotation: 0,
      text: "this month",
      fontFamily: "Inter",
      fontSize: 28,
      color: "#A78BFA",
      align: "left",
      letterSpacing: 6,
      weight: 600,
    },
    {
      id: "tpl-num-cover-title",
      kind: "text",
      z: 2,
      x: 100,
      y: 360,
      width: 880,
      height: 540,
      rotation: 0,
      text: "3 books I\nwon't shut up\nabout.",
      fontFamily: "Playfair Display",
      fontSize: 136,
      color: "#1B1B1F",
      align: "left",
      weight: 700,
    },

    // ── Slide 1 — entry 01 ──────────────────────────────────────────
    {
      id: "tpl-num-1-card",
      kind: "shape",
      shape: "rect",
      z: 1,
      x: W + 80,
      y: 240,
      width: 920,
      height: 880,
      rotation: 0,
      fill: "#FFFFFF",
      cornerRadius: 24,
    },
    {
      id: "tpl-num-1-index",
      kind: "text",
      z: 2,
      x: W + 130,
      y: 290,
      width: 200,
      height: 100,
      rotation: 0,
      text: "01",
      fontFamily: "Bebas Neue",
      fontSize: 96,
      color: "#A78BFA",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-num-1-title",
      kind: "text",
      z: 3,
      x: W + 130,
      y: 470,
      width: 820,
      height: 220,
      rotation: 0,
      text: "Atomic Habits",
      fontFamily: "Playfair Display",
      fontSize: 84,
      color: "#1B1B1F",
      align: "left",
      weight: 700,
    },
    {
      id: "tpl-num-1-author",
      kind: "text",
      z: 4,
      x: W + 130,
      y: 720,
      width: 820,
      height: 60,
      rotation: 0,
      text: "James Clear",
      fontFamily: "Inter",
      fontSize: 32,
      color: "#4B5563",
      align: "left",
      weight: 500,
    },
    {
      id: "tpl-num-1-note",
      kind: "text",
      z: 5,
      x: W + 130,
      y: 820,
      width: 820,
      height: 240,
      rotation: 0,
      text: "Two-minute rule, identity-based habits, and a system that survives bad days. I re-read it every spring.",
      fontFamily: "Inter",
      fontSize: 28,
      color: "#6B7280",
      align: "left",
      weight: 400,
    },

    // ── Slide 2 — entry 02 ──────────────────────────────────────────
    {
      id: "tpl-num-2-card",
      kind: "shape",
      shape: "rect",
      z: 1,
      x: 2 * W + 80,
      y: 240,
      width: 920,
      height: 880,
      rotation: 0,
      fill: "#FFFFFF",
      cornerRadius: 24,
    },
    {
      id: "tpl-num-2-index",
      kind: "text",
      z: 2,
      x: 2 * W + 130,
      y: 290,
      width: 200,
      height: 100,
      rotation: 0,
      text: "02",
      fontFamily: "Bebas Neue",
      fontSize: 96,
      color: "#A78BFA",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-num-2-title",
      kind: "text",
      z: 3,
      x: 2 * W + 130,
      y: 470,
      width: 820,
      height: 220,
      rotation: 0,
      text: "Hyperion",
      fontFamily: "Playfair Display",
      fontSize: 84,
      color: "#1B1B1F",
      align: "left",
      weight: 700,
    },
    {
      id: "tpl-num-2-author",
      kind: "text",
      z: 4,
      x: 2 * W + 130,
      y: 720,
      width: 820,
      height: 60,
      rotation: 0,
      text: "Dan Simmons",
      fontFamily: "Inter",
      fontSize: 32,
      color: "#4B5563",
      align: "left",
      weight: 500,
    },
    {
      id: "tpl-num-2-note",
      kind: "text",
      z: 5,
      x: 2 * W + 130,
      y: 820,
      width: 820,
      height: 240,
      rotation: 0,
      text: "Seven travelers, seven tales, one impossible deadline. Reads like Canterbury Tales reborn as space opera.",
      fontFamily: "Inter",
      fontSize: 28,
      color: "#6B7280",
      align: "left",
      weight: 400,
    },
  ],
};
