import type { Template } from "../types";

/**
 * 3-slide portrait carousel framing a single pull-quote: cover quote
 * → attribution + context → call to action.
 * Slide dims: 1080 × 1350.
 */
const W = 1080;

export const template: Template = {
  id: "ig-portrait-quote",
  name: "Pull Quote",
  description: "Hero quote, attribution + context, then a soft CTA.",
  presetId: "ig-portrait",
  slideCount: 3,
  tags: ["quote", "minimal"],
  background: {
    kind: "gradient",
    angle: 135,
    stops: [
      { offset: 0, color: "#1F1B2E" },
      { offset: 1, color: "#0E1015" },
    ],
  },
  elements: [
    // ── Slide 0 — the quote ─────────────────────────────────────────
    {
      id: "tpl-quote-cover-mark",
      kind: "text",
      z: 1,
      x: 90,
      y: 200,
      width: 160,
      height: 200,
      rotation: 0,
      text: "“",
      fontFamily: "Cormorant Garamond",
      fontSize: 280,
      color: "#A78BFA",
      align: "left",
      weight: 600,
    },
    {
      id: "tpl-quote-cover-body",
      kind: "text",
      z: 2,
      x: 90,
      y: 360,
      width: 900,
      height: 760,
      rotation: 0,
      text: "The work of artists is not to be original. It is to be honest.",
      fontFamily: "Cormorant Garamond",
      fontSize: 92,
      color: "#F4F4F8",
      align: "left",
      weight: 400,
    },

    // ── Slide 1 — attribution + context ─────────────────────────────
    {
      id: "tpl-quote-1-rule",
      kind: "shape",
      shape: "rect",
      z: 1,
      x: W + 90,
      y: 280,
      width: 80,
      height: 4,
      rotation: 0,
      fill: "#A78BFA",
    },
    {
      id: "tpl-quote-1-author",
      kind: "text",
      z: 2,
      x: W + 90,
      y: 320,
      width: 900,
      height: 90,
      rotation: 0,
      text: "Marina Abramović",
      fontFamily: "Inter",
      fontSize: 44,
      color: "#F4F4F8",
      align: "left",
      weight: 600,
    },
    {
      id: "tpl-quote-1-role",
      kind: "text",
      z: 3,
      x: W + 90,
      y: 410,
      width: 900,
      height: 60,
      rotation: 0,
      text: "Performance artist",
      fontFamily: "Inter",
      fontSize: 28,
      color: "#9CA3AF",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-quote-1-context",
      kind: "text",
      z: 4,
      x: W + 90,
      y: 580,
      width: 900,
      height: 540,
      rotation: 0,
      text: "Said during a 2014 lecture at the Serpentine Galleries — a reminder that originality, when forced, is just performance.",
      fontFamily: "Cormorant Garamond",
      fontSize: 48,
      color: "#D5D6DC",
      align: "left",
      weight: 400,
    },

    // ── Slide 2 — CTA ───────────────────────────────────────────────
    {
      id: "tpl-quote-2-text",
      kind: "text",
      z: 1,
      x: 2 * W + 90,
      y: 420,
      width: 900,
      height: 240,
      rotation: 0,
      text: "Tag someone\nwho needs this\nthis week.",
      fontFamily: "Cormorant Garamond",
      fontSize: 84,
      color: "#F4F4F8",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-quote-2-handle",
      kind: "text",
      z: 2,
      x: 2 * W + 90,
      y: 1180,
      width: 900,
      height: 50,
      rotation: 0,
      text: "Follow @yourhandle for more",
      fontFamily: "Inter",
      fontSize: 26,
      color: "#9CA3AF",
      align: "left",
      weight: 500,
    },
  ],
};
