import type { Template } from "../types";

/**
 * 3-slide carousel: hook, side-by-side before/after, takeaway. Uses
 * filled rects as colored blocks rather than image placeholders so
 * the template is fully self-contained (no asset references).
 */
export const template: Template = {
  id: "ig-square-before-after",
  name: "Before / After",
  description: "Hook slide, side-by-side comparison blocks, then a takeaway slide.",
  presetId: "ig-square",
  slideCount: 3,
  tags: ["comparison", "case-study"],
  background: { kind: "solid", color: "#F4F1EA" },
  elements: [
    // ── Slide 0 — hook ──────────────────────────────────────────────
    {
      id: "tpl-ba-cover-title",
      kind: "text",
      z: 2,
      x: 100,
      y: 380,
      width: 880,
      height: 320,
      rotation: 0,
      text: "Before vs After",
      fontFamily: "Playfair Display",
      fontSize: 156,
      color: "#1B1B1F",
      align: "left",
      weight: 700,
    },
    {
      id: "tpl-ba-cover-subtitle",
      kind: "text",
      z: 3,
      x: 100,
      y: 720,
      width: 880,
      height: 90,
      rotation: 0,
      text: "Two weeks of redesign, side by side",
      fontFamily: "Inter",
      fontSize: 36,
      color: "#4B5563",
      align: "left",
      weight: 500,
    },

    // ── Slide 1 — comparison ────────────────────────────────────────
    {
      id: "tpl-ba-1-left-bg",
      kind: "shape",
      shape: "rect",
      z: 1,
      x: 1080 + 60,
      y: 240,
      width: 440,
      height: 600,
      rotation: 0,
      fill: "#C4C7CC",
      cornerRadius: 16,
    },
    {
      id: "tpl-ba-1-right-bg",
      kind: "shape",
      shape: "rect",
      z: 1,
      x: 1080 + 580,
      y: 240,
      width: 440,
      height: 600,
      rotation: 0,
      fill: "#3F3D56",
      cornerRadius: 16,
    },
    {
      id: "tpl-ba-1-left-label",
      kind: "text",
      z: 2,
      x: 1080 + 60,
      y: 860,
      width: 440,
      height: 60,
      rotation: 0,
      text: "BEFORE",
      fontFamily: "Bebas Neue",
      fontSize: 56,
      color: "#1B1B1F",
      align: "center",
      letterSpacing: 6,
      weight: 400,
    },
    {
      id: "tpl-ba-1-right-label",
      kind: "text",
      z: 2,
      x: 1080 + 580,
      y: 860,
      width: 440,
      height: 60,
      rotation: 0,
      text: "AFTER",
      fontFamily: "Bebas Neue",
      fontSize: 56,
      color: "#A78BFA",
      align: "center",
      letterSpacing: 6,
      weight: 400,
    },

    // ── Slide 2 — takeaway ──────────────────────────────────────────
    {
      id: "tpl-ba-2-eyebrow",
      kind: "text",
      z: 2,
      x: 2160 + 100,
      y: 260,
      width: 880,
      height: 50,
      rotation: 0,
      text: "The shift",
      fontFamily: "Inter",
      fontSize: 28,
      color: "#A78BFA",
      align: "left",
      letterSpacing: 6,
      weight: 600,
    },
    {
      id: "tpl-ba-2-body",
      kind: "text",
      z: 3,
      x: 2160 + 100,
      y: 340,
      width: 880,
      height: 560,
      rotation: 0,
      text: "Stop designing in isolation.\nShow rough work early.\nIterate in public.",
      fontFamily: "Playfair Display",
      fontSize: 84,
      color: "#1B1B1F",
      align: "left",
      weight: 700,
    },
  ],
};
