import type { Template } from "../types";

/**
 * 3-slide carousel: cover + two numbered tips. Bold serif display.
 * Looks like an editorial pull-quote series — works for almost any
 * "X things I learned about Y" hook.
 */
export const template: Template = {
  id: "ig-square-tips-list",
  name: "Tips List",
  description: "Cover + two big-numbered tips. Easy to extend by duplicating slide 2.",
  presetId: "ig-square",
  slideCount: 3,
  tags: ["editorial", "list"],
  background: { kind: "solid", color: "#0E1015" },
  elements: [
    // ── Slide 0 — cover ─────────────────────────────────────────────
    {
      id: "tpl-tips-cover-eyebrow",
      kind: "text",
      z: 1,
      x: 80,
      y: 220,
      width: 920,
      height: 60,
      rotation: 0,
      text: "Field notes",
      fontFamily: "Space Grotesk",
      fontSize: 28,
      color: "#A78BFA",
      align: "left",
      letterSpacing: 6,
      weight: 500,
    },
    {
      id: "tpl-tips-cover-title",
      kind: "text",
      z: 2,
      x: 80,
      y: 300,
      width: 920,
      height: 460,
      rotation: 0,
      text: "5 things I\nlearned about\nbuilding solo.",
      fontFamily: "DM Serif Display",
      fontSize: 128,
      color: "#F4F4F8",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-tips-cover-swipe",
      kind: "text",
      z: 3,
      x: 80,
      y: 940,
      width: 920,
      height: 50,
      rotation: 0,
      text: "Swipe →",
      fontFamily: "Inter",
      fontSize: 28,
      color: "#9CA3AF",
      align: "left",
      weight: 500,
    },

    // ── Slide 1 — tip 01 ────────────────────────────────────────────
    {
      id: "tpl-tips-1-rule",
      kind: "shape",
      shape: "rect",
      z: 1,
      x: 1080 + 80,
      y: 220,
      width: 80,
      height: 6,
      rotation: 0,
      fill: "#A78BFA",
    },
    {
      id: "tpl-tips-1-number",
      kind: "text",
      z: 2,
      x: 1080 + 80,
      y: 250,
      width: 300,
      height: 200,
      rotation: 0,
      text: "01",
      fontFamily: "DM Serif Display",
      fontSize: 200,
      color: "#A78BFA",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-tips-1-headline",
      kind: "text",
      z: 3,
      x: 1080 + 80,
      y: 480,
      width: 920,
      height: 220,
      rotation: 0,
      text: "Ship the smallest version that someone could use.",
      fontFamily: "DM Serif Display",
      fontSize: 80,
      color: "#F4F4F8",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-tips-1-body",
      kind: "text",
      z: 4,
      x: 1080 + 80,
      y: 780,
      width: 920,
      height: 160,
      rotation: 0,
      text: "Polish kills momentum. Get the rough version in front of a real person before you fall in love with the wrong details.",
      fontFamily: "Inter",
      fontSize: 32,
      color: "#9CA3AF",
      align: "left",
      weight: 400,
    },

    // ── Slide 2 — tip 02 ────────────────────────────────────────────
    {
      id: "tpl-tips-2-rule",
      kind: "shape",
      shape: "rect",
      z: 1,
      x: 2160 + 80,
      y: 220,
      width: 80,
      height: 6,
      rotation: 0,
      fill: "#A78BFA",
    },
    {
      id: "tpl-tips-2-number",
      kind: "text",
      z: 2,
      x: 2160 + 80,
      y: 250,
      width: 300,
      height: 200,
      rotation: 0,
      text: "02",
      fontFamily: "DM Serif Display",
      fontSize: 200,
      color: "#A78BFA",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-tips-2-headline",
      kind: "text",
      z: 3,
      x: 2160 + 80,
      y: 480,
      width: 920,
      height: 220,
      rotation: 0,
      text: "Talk to one user every day.",
      fontFamily: "DM Serif Display",
      fontSize: 80,
      color: "#F4F4F8",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-tips-2-body",
      kind: "text",
      z: 4,
      x: 2160 + 80,
      y: 780,
      width: 920,
      height: 160,
      rotation: 0,
      text: "Direct messages, not surveys. A five-minute reply beats a thirty-question form.",
      fontFamily: "Inter",
      fontSize: 32,
      color: "#9CA3AF",
      align: "left",
      weight: 400,
    },
  ],
};
