import type { Template } from "../types";

/**
 * Single-slide vertical story / reels cover. 1080 × 1920.
 * Stacked-headline format with an accent block at the bottom.
 */
export const template: Template = {
  id: "ig-story-cover",
  name: "Story Cover",
  description: "Vertical hero with stacked headline and a tappable-looking CTA block.",
  presetId: "ig-story",
  slideCount: 1,
  tags: ["story", "cover"],
  background: {
    kind: "gradient",
    angle: 160,
    stops: [
      { offset: 0, color: "#241E3A" },
      { offset: 1, color: "#0E1015" },
    ],
  },
  elements: [
    {
      id: "tpl-story-eyebrow",
      kind: "text",
      z: 1,
      x: 80,
      y: 300,
      width: 920,
      height: 60,
      rotation: 0,
      text: "new this week",
      fontFamily: "Inter",
      fontSize: 28,
      color: "#A78BFA",
      align: "left",
      letterSpacing: 6,
      weight: 600,
    },
    {
      id: "tpl-story-title",
      kind: "text",
      z: 2,
      x: 80,
      y: 380,
      width: 920,
      height: 1000,
      rotation: 0,
      text: "How I\nactually\nplan a\nproject.",
      fontFamily: "DM Serif Display",
      fontSize: 180,
      color: "#F4F4F8",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-story-cta-bg",
      kind: "shape",
      shape: "rect",
      z: 3,
      x: 80,
      y: 1640,
      width: 920,
      height: 140,
      rotation: 0,
      fill: "#A78BFA",
      cornerRadius: 999,
    },
    {
      id: "tpl-story-cta-text",
      kind: "text",
      z: 4,
      x: 80,
      y: 1680,
      width: 920,
      height: 60,
      rotation: 0,
      text: "Tap to watch  →",
      fontFamily: "Inter",
      fontSize: 36,
      color: "#1B1138",
      align: "center",
      weight: 700,
    },
  ],
};
