import type { Template } from "../types";

/**
 * 5-slide LinkedIn carousel: hook → three numbered insights → CTA.
 * Slide dims: 1080 × 1080.
 */
const W = 1080;

export const template: Template = {
  id: "linkedin-thought-leader",
  name: "Thought Leader",
  description: "Hook, three insights, soft CTA — the classic LinkedIn carousel arc.",
  presetId: "linkedin-carousel",
  slideCount: 5,
  tags: ["thought-leadership", "deck"],
  background: { kind: "solid", color: "#FFFFFF" },
  elements: [
    // ── Slide 0 — hook ──────────────────────────────────────────────
    {
      id: "tpl-li-cover-eyebrow",
      kind: "text",
      z: 1,
      x: 80,
      y: 240,
      width: 920,
      height: 50,
      rotation: 0,
      text: "leadership",
      fontFamily: "Inter",
      fontSize: 24,
      color: "#0A66C2",
      align: "left",
      letterSpacing: 6,
      weight: 700,
    },
    {
      id: "tpl-li-cover-title",
      kind: "text",
      z: 2,
      x: 80,
      y: 320,
      width: 920,
      height: 500,
      rotation: 0,
      text: "Three habits\nseparating great\nmanagers from\ngood ones.",
      fontFamily: "Manrope",
      fontSize: 88,
      color: "#0A1B2C",
      align: "left",
      weight: 700,
    },
    {
      id: "tpl-li-cover-swipe",
      kind: "text",
      z: 3,
      x: 80,
      y: 940,
      width: 920,
      height: 50,
      rotation: 0,
      text: "Swipe →",
      fontFamily: "Inter",
      fontSize: 26,
      color: "#637381",
      align: "left",
      weight: 500,
    },

    // ── Slides 1-3 — insights ───────────────────────────────────────
    ...insightSlide(1, "01", "They schedule decision time, not meetings.", "Calendar real estate goes to thinking, not status. Status moves to docs."),
    ...insightSlide(2, "02", "They write the brief before the meeting.", "If you can't write it in two paragraphs, the conversation isn't ready yet."),
    ...insightSlide(3, "03", "They ship one decision a week, in writing.", "A team that knows what's decided moves twice as fast as one that's guessing."),

    // ── Slide 4 — CTA ───────────────────────────────────────────────
    {
      id: "tpl-li-cta-title",
      kind: "text",
      z: 1,
      x: 4 * W + 80,
      y: 360,
      width: 920,
      height: 360,
      rotation: 0,
      text: "Which one are\nyou trying first?",
      fontFamily: "Manrope",
      fontSize: 88,
      color: "#0A1B2C",
      align: "left",
      weight: 700,
    },
    {
      id: "tpl-li-cta-handle",
      kind: "text",
      z: 2,
      x: 4 * W + 80,
      y: 780,
      width: 920,
      height: 60,
      rotation: 0,
      text: "Reply below — I'll DM you a one-pager.",
      fontFamily: "Inter",
      fontSize: 28,
      color: "#637381",
      align: "left",
      weight: 500,
    },
    {
      id: "tpl-li-cta-rule",
      kind: "shape",
      shape: "rect",
      z: 3,
      x: 4 * W + 80,
      y: 900,
      width: 80,
      height: 6,
      rotation: 0,
      fill: "#0A66C2",
    },
    {
      id: "tpl-li-cta-author",
      kind: "text",
      z: 4,
      x: 4 * W + 80,
      y: 930,
      width: 920,
      height: 50,
      rotation: 0,
      text: "Your name — Your role",
      fontFamily: "Inter",
      fontSize: 24,
      color: "#0A1B2C",
      align: "left",
      weight: 600,
    },
  ],
};

function insightSlide(slideIdx: number, number: string, headline: string, body: string) {
  const x = slideIdx * W;
  return [
    {
      id: `tpl-li-${slideIdx}-rule`,
      kind: "shape" as const,
      shape: "rect" as const,
      z: 1,
      x: x + 80,
      y: 240,
      width: 80,
      height: 6,
      rotation: 0,
      fill: "#0A66C2",
    },
    {
      id: `tpl-li-${slideIdx}-number`,
      kind: "text" as const,
      z: 2,
      x: x + 80,
      y: 280,
      width: 300,
      height: 120,
      rotation: 0,
      text: number,
      fontFamily: "Manrope",
      fontSize: 84,
      color: "#0A66C2",
      align: "left" as const,
      weight: 700 as const,
    },
    {
      id: `tpl-li-${slideIdx}-headline`,
      kind: "text" as const,
      z: 3,
      x: x + 80,
      y: 440,
      width: 920,
      height: 300,
      rotation: 0,
      text: headline,
      fontFamily: "Manrope",
      fontSize: 64,
      color: "#0A1B2C",
      align: "left" as const,
      weight: 700 as const,
    },
    {
      id: `tpl-li-${slideIdx}-body`,
      kind: "text" as const,
      z: 4,
      x: x + 80,
      y: 800,
      width: 920,
      height: 200,
      rotation: 0,
      text: body,
      fontFamily: "Inter",
      fontSize: 28,
      color: "#637381",
      align: "left" as const,
      weight: 400 as const,
    },
  ];
}
