import type { Template } from "../types";

/**
 * Single-slide TikTok cover. 1080 × 1920.
 * Punchy display-font hook with a numbered streak corner badge.
 */
export const template: Template = {
  id: "tiktok-cover",
  name: "TikTok Hook",
  description: "Bold caps headline + 'part of a series' badge for serialized content.",
  presetId: "tiktok-cover",
  slideCount: 1,
  tags: ["cover", "series"],
  background: { kind: "solid", color: "#FCE54B" },
  elements: [
    {
      id: "tpl-tt-badge-bg",
      kind: "shape",
      shape: "rect",
      z: 1,
      x: 80,
      y: 240,
      width: 280,
      height: 80,
      rotation: 0,
      fill: "#1B1B1F",
      cornerRadius: 999,
    },
    {
      id: "tpl-tt-badge-text",
      kind: "text",
      z: 2,
      x: 80,
      y: 264,
      width: 280,
      height: 36,
      rotation: 0,
      text: "PART 03 / 05",
      fontFamily: "Inter",
      fontSize: 24,
      color: "#FCE54B",
      align: "center",
      letterSpacing: 4,
      weight: 700,
    },
    {
      id: "tpl-tt-headline",
      kind: "text",
      z: 3,
      x: 80,
      y: 520,
      width: 920,
      height: 1100,
      rotation: 0,
      text: "Three\nminutes\nof real\nadvice.",
      fontFamily: "Bebas Neue",
      fontSize: 260,
      color: "#1B1B1F",
      align: "left",
      letterSpacing: 4,
      weight: 400,
    },
    {
      id: "tpl-tt-handle",
      kind: "text",
      z: 4,
      x: 80,
      y: 1740,
      width: 920,
      height: 50,
      rotation: 0,
      text: "@yourhandle",
      fontFamily: "Inter",
      fontSize: 32,
      color: "#1B1B1F",
      align: "left",
      weight: 600,
    },
  ],
};
