import type { Template } from "../types";

/**
 * Single-slide X / Twitter image post. 1600 × 900.
 * Landscape announcement layout: kicker, headline, supporting detail.
 */
export const template: Template = {
  id: "x-post-announcement",
  name: "Announcement",
  description: "Landscape kicker + headline + footer for launches, releases, and milestones.",
  presetId: "x-post",
  slideCount: 1,
  tags: ["announcement", "launch"],
  background: { kind: "solid", color: "#0E1015" },
  elements: [
    {
      id: "tpl-xp-rule",
      kind: "shape",
      shape: "rect",
      z: 1,
      x: 100,
      y: 120,
      width: 80,
      height: 6,
      rotation: 0,
      fill: "#A78BFA",
    },
    {
      id: "tpl-xp-kicker",
      kind: "text",
      z: 2,
      x: 100,
      y: 160,
      width: 1400,
      height: 60,
      rotation: 0,
      text: "now live",
      fontFamily: "Inter",
      fontSize: 28,
      color: "#A78BFA",
      align: "left",
      letterSpacing: 6,
      weight: 700,
    },
    {
      id: "tpl-xp-headline",
      kind: "text",
      z: 3,
      x: 100,
      y: 250,
      width: 1400,
      height: 360,
      rotation: 0,
      text: "Folio just\nshipped templates.",
      fontFamily: "DM Serif Display",
      fontSize: 144,
      color: "#F4F4F8",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-xp-body",
      kind: "text",
      z: 4,
      x: 100,
      y: 680,
      width: 1100,
      height: 80,
      rotation: 0,
      text: "Start from a layout you like, then make it yours.",
      fontFamily: "Inter",
      fontSize: 32,
      color: "#9CA3AF",
      align: "left",
      weight: 400,
    },
    {
      id: "tpl-xp-handle",
      kind: "text",
      z: 5,
      x: 100,
      y: 800,
      width: 1400,
      height: 50,
      rotation: 0,
      text: "folio.app · @folioapp",
      fontFamily: "JetBrains Mono",
      fontSize: 24,
      color: "#6B7280",
      align: "left",
      weight: 400,
    },
  ],
};
